---
title: "rubric"
author: "pmcdevitt"
date: "4 décembre 2017"
output: html_document
---

## Business Understanding (10 points total).  
• [10 points] Describe the purpose of the data set you selected (i.e., why was this data
collected in the first place?).  
How will you measure the effectiveness of a good algorithm ?  
Why does your chosen validation method make sense for this specific dataset and the stakeholders needs?  

##Data Understanding (20 points total)  
• [10 points] Describe the meaning and type of data (scale, values, etc.) for each attribute in the data file.   Verify data quality:  
  Are there missing values?  
  Duplicate data?  
  Outliers?  
  Are those mistakes?  
  How do you deal with these problems? 
• [10 points] Visualize the any important attributes appropriately. Important: Provide an interpretation for any charts or graphs. 

## Modeling and Evaluation (50 points total)  

Be as thorough as possible when analyzing the data you have chosen and use visualizations of the results to explain the performance and expected outcomes whenever possible. Guide the reader through your analysis with plenty of discussion of the results.  
Each option is broken down by:
• [10 Points] Train and adjust parameters
• [10 Points] Evaluate and Compare
• [10 Points] Visualize Results
• [20 Points] Summarize the Ramifications
•
••
### Option A: Cluster Analysis  
• Train: Perform cluster analysis using several clustering methods (adjust parameters).  
• Eval: Use internal and/or external validation measures to describe and compare the clusterings and the clusters— how did you determine a suitable number of clusters for each method ?  
• Visualize: Use tables/visualization to discuss the found results. Explain each visualization in detail.  
• Summarize: Describe your results. What findings are the most interesting and why ?  

## Deployment (10 points total)  
• Be critical of your performance and tell the reader how you current model might be usable by other parties.  
Did you achieve your goals?  
If not, can you reign in the utility of your modeling?  
How useful is your model for interested parties (i.e., the companies or organizations that might want to use it) ?   
How would your deploy your model for interested parties ?  
• What other data should be collected ?  
How often would the model need to be updated, etc. ?  

##  Exceptional Work (10 points total)

• You have free reign to provide additional analyses or combine analyses.  


Option B: Association Rule Mining
• Train: Create frequent itemsets and association rules (adjust parameters).
• Eval: Use several measure for evaluating how interesting different rules are.
• Visualize: Use tables/visualization to discuss the found results.
• Summarize: Describe your results. What findings are the most compelling and why?
Option C: Collaborative Filtering
• Train: Create user-item matrices or item-item matrices using collaborative filtering
(adjust parameters).
• Eval: Determine performance of the recommendations using different performance
measures (explain the ramifications of each measure).
• Visualize: Use tables/visualization to discuss the found results. Explain each
visualization in detail.
• Summarize: Describe your results. What findings are the most compelling and why?
