---
title: "deployment"
output: html_document
---

### __Deployment__  

#### Usefulness  

The usefulness of this model is to provide guidance as to which articles are to be published on the mashable.com web-site. One facet of Mashable's business model is to generate revenue by selling advertising and sponsored content on the mashable.com web-site. The value of the site to advertisers, and the revenue stream that can be protected for mashable, can be measured by the number of articles that mashable readers share with their on-line social media network. The value of this classification model is to identify the site content with higher likelihood of being popularly shared within the the target audience. 

#### Measurement of model value  
 
A way to measure the model's value is by monitoring the success of the prediction model in terms of increasing social media shares from mashable published articles. Since there can be many (very many !) factors influencing the popularity (number of shares) of articles that are beyond the applicability scope of the model, it is recommended that the value measurement be assessed by controlled A/B releases of content that is decided by current methods, side-by-side, with content that is recommended with this classification. By using a side-by-side A/B evaluation, the effectiveness of the classification model for improving content recommendations can be credibly assessed.


#### Deployment method / external data support  
 
 The current vision for deployment of the model includes these elements :  
 - a web-based user interface in which the user (the article author or other proposer) can deposit the article (title, content, embedded images and videos) in similar fashion as DropBox or other similar media-sharing file servers  
 - a parsing / feature extraction machine deployed at the shared file server site  
     - the model requires the extraction of several explanatory variables (feature extraction) from the content of the article in order to evaluate the article's popularity score in the model  
         - among the features to be extracted from the article as model inputs are the following :  
             * key-word statistics, positive and negative sentiment counts, LDA_00 --> LDA_04 scores, number of images and number of videos, sentiment polarity based on title, related hyperlink references  
         - a feature extraction machine will be deployed at the file server site to process the article content and provide the model inputs  
         - in addition, another element of the deployment is to assign the article to an appropriate data channel (e.g., Social Media, Technology, Business). this will also be an element deployed on the file server site. the text and title will be processed through a text-mining approach to evaluate the appropriate data channel.  
         
  - once the key features have been developed from the text processing machines, then all of the inputs for the classification model are available and can be executed  
  
  - the concept of the deployment is :  
    * the article is uploaded to the submittal site,  
    * the feature extraction machine is launched, then  
    * the popularity classification model is executed, and  
    * the recommendation to publish or not to publish is provided to the mashable content editor.  
    * the execution time associated to this activity is anticipated to be real-time, within less than a few seconds.  
    
  - the goal of the application is that the article, with only some minimal contextual information (requested publication date, author contact information) is sufficient to provide a __publish / no-publish recommendation__ to the content editor;  
  - the goal is that there is no need for external data gathering to feed the model in the production environment  
  
 
#### Model Updates  

 - this model is intended to estimate the _mashable_ readers' perceptions of what is interesting and relevant to share with their social media network  
 - although the model's basic input features are attempting to capture and use elements that have a certain temporal durability (positive and negative sentiments, domain segregation of vocabulary, hyper-link reference counts) the fact remains that what is popular in this moment is an ever-evolving situation. Because of that, the recommendation is that, at the initial deployment phases, the model characteristics be updated on a monthly basis. Monitoring for evolution of the model charactersitic changes will provide relevant information as to the frequency of updates going forward - either more frequent or less frequent.  
 - longer term, the survivability of this model will be dependent on the ability to deploy this model in a manner that can incorporate reinforcement learning methods. the rapidly evolving nature of what is interesting or not interesting to contemporary society is the heart of the 

        
