---
title: "data_prep - mashable"
author: "patrick mcdevitt"
date: "5 sep 2017"
output: html_document
classoption: landscape
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)


rm(list=ls())

library(lubridate)
library(MASS)
library(car)
library(moments)
library(ggplot2)
library(plyr)

home_dir <- "~/_smu/_src/mashable/"
setwd(home_dir)
data_dir <- "./data"
eda_dir <- "./eda"

```


```{r read data, include = TRUE, message = FALSE}

	setwd(home_dir)
	setwd(data_dir)

	mash <- read.csv("OnlineNewsPopularity.csv")
	setwd(home_dir)

	names(mash) <- tolower(names(mash))
	
	for (i in 1:(length(mash)))
	{
		if (class(mash[,i]) == "character")
		{
			mash[,i] <- factor(mash[,i])
		}
	}
```

***  
Please include this citation if you plan to use this database:  
 
    K. Fernandes, P. Vinagre and P. Cortez. A Proactive Intelligent Decision
    Support System for Predicting the Popularity of Online News. Proceedings
    of the 17th EPIA 2015 - Portuguese Conference on Artificial Intelligence,
    September, Coimbra, Portugal.  
***  

```{r remove outliers, include = TRUE, message = FALSE}

# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	remove outliers ... more than 5 sigma from mean value
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
	
	lst <- length(mash)	#
	
	for (i in 1 : lst)
	{
		if(class(mash[,i]) == "integer" || class(mash[,i]) == "numeric")
		{
			mash[,i][which(scale(mash[,i]) > 5)] <- NA
			mash[,i][which(scale(mash[,i]) < -5)] <- NA
		}
	}

```



```{r add some variables}

# ... add day_of_week column from boolean daily columns

  mash$day_of_week <- "01_Mon"
  mash$day_of_week[which(mash$weekday_is_tuesday == 1)] <- "02_Tue"
  mash$day_of_week[which(mash$weekday_is_wednesday == 1)] <- "03_Wed"
  mash$day_of_week[which(mash$weekday_is_thursday == 1)] <- "04_Thu"
  mash$day_of_week[which(mash$weekday_is_friday == 1)] <- "05_Fri"
  mash$day_of_week[which(mash$weekday_is_saturday == 1)] <- "06_Sat"
  mash$day_of_week[which(mash$weekday_is_sunday == 1)] <- "07_Sun"
  mash$day_of_week <- as.factor(mash$day_of_week)

# ... add data_channel column from boolean data_channel columns

  mash$data_channel <- "LifeStyle"
  mash$data_channel[which(mash$data_channel_is_entertainment == 1)] <- "Entertainment"
  mash$data_channel[which(mash$data_channel_is_bus == 1)] <- "Business"
  mash$data_channel[which(mash$data_channel_is_socmed == 1)] <- "SocMed"
  mash$data_channel[which(mash$data_channel_is_tech == 1)] <- "Tech"
  mash$data_channel[which(mash$data_channel_is_world == 1)] <- "World"
  mash$data_channel <- as.factor(mash$data_channel)
  
  
# ... add log_shares

  mash$log_shares <- log(mash$shares)
  
  
```

```{r drop no information columns} 

#	mash <- subset(mash, select = -c(team_id, team_name, game_event_id, game_id))

```


```{r raw data tabular summary, message = FALSE}

	summary_tbl <- data.frame(x = character(0), stats = character(0))

	for (i in 2 : length(mash))
	{
		if(class(mash[,i]) == "integer" || class(mash[,i]) == "numeric")
		{
			new_row <- data.frame(x = names(mash[i]),
								  stats = sprintf (
								  	 "| %8d | %8d | %8.1f | %8.1f | %8.1f | %8.1f | %8.3f | ", 
									colSums(!is.na(mash[i])),
									(dim(mash)[1] - colSums(!is.na(mash[i]))),
								  	mean(mash[,i], na.rm = TRUE),
								  	median(mash[,i], na.rm = TRUE),
								  	max(mash[,i], na.rm = TRUE),
								  	min(mash[,i], na.rm = TRUE),
								  	skewness(mash[,i], na.rm = TRUE)
								  	)
								  )
			summary_tbl <- rbind(summary_tbl, new_row)
		}
	}

	summary_tbl
	
```


```{r plot base data, echo = FALSE, message = FALSE, comment = "", fig.width = 12}

  setwd(home_dir)
  setwd(eda_dir)
  
#  sorted_by_shares <- mash[order(mash$shares),]

# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	make some plots for numeric variables .....
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

	cx_scale = 2.5
# ... 	use cx_scale = 1 for in-line html knitted docs
# ...	use cx_scale = 3 for pdf landscape mode knitted docs

	par (mfrow = c (1, 1))

	png (filename = "log_shares_%02d.png", width = 1800, height = 600)
	plot(mash$log_shares, col = "slateblue",
		cex = cx_scale, cex.lab = cx_scale, cex.axis = cx_scale, cex.main = cx_scale,
	  	xlab = names(mash[i]),
	  	main = "Dependent variable - log(shares)")
	dev.off()

	for (i in 2 : length(mash))
	{
		if(class(mash[,i]) == "integer"
		   					|| class(mash[,i]) == "numeric"
		   					|| class(mash[,i]) == "matrix")
		{
			png (filename = paste0(names(mash[i]), "_%02d.png"), width = 1800, height = 600)
			par (mfrow = c (1, 4))

			plot(mash[,i], col = "dodgerblue4",
				 cex = cx_scale, cex.lab = cx_scale, cex.axis = cx_scale, cex.main = cx_scale,
				  	xlab = names(mash[i]),
				  	main = "Independent variable sequence")

			hist(mash[,i], main = names(mash[i]), cex.lab = cx_scale, cex.main = cx_scale)
			if (skewness(mash[,i], na.rm = TRUE) < 0)
			{
				txt_pos <- "topleft"
			}
			else {
				txt_pos <- "topright"
			}
			legend(txt_pos, legend = c(paste("Mean =", round(mean(mash[,i], na.rm = TRUE), 1)),
                            paste("Median =",round(median(mash[,i], na.rm = TRUE), 1)),
                            paste("Std.Dev =", round(sd(mash[,i], na.rm = TRUE), 1)), 
                            paste("Skewness =", round(skewness(mash[,i], na.rm = TRUE), 1))), 
                  bty = "n", cex = cx_scale)
			
			
			plot(mash$log_shares  ~ mash[,i],
				 		col = "darkslateblue",
				 		cex = cx_scale,
				 		cex.lab = cx_scale,
				 		cex.axis = cx_scale,
				 		cex.main = cx_scale,
				 	ylab = "log(Shares)",
				  	xlab = names(mash[i]),
				  	main = "Independent variable vs. Shares")
			abline(lm(mash$log_shares ~ mash[,i]))

# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	look at residuals from one-variable linear fit			
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

			fit <- lm(mash$log_shares ~ mash[,i], na.action = na.exclude)
			res <- resid(fit)
			plot (mash[,i], res, cex = cx_scale, cex.lab = cx_scale, cex.axis = cx_scale, cex.main = cx_scale,
				  ylab = "Residuals",
				  xlab = names(mash[i]),
				  main = "Residuals from Linear Fit",
				  col = "darkorchid")
			abline (0, 0)
			
			dev.off()
			
		}
	}

	
	for (i in 2:(length(mash)))
	{
		if(class(mash[,i]) == "factor")
		{
			png (filename = paste0(names(mash[i]), "_%02d.png"), width = 1800, height = 600)
  		par (mfrow = c (2, 2))

  		plot_title <- names(mash[i])

			p <- ggplot(mash, aes(x = mash[,i], fill = mash[,i])) + 
				geom_bar() + labs(title = plot_title)
			print(p)

			p <- ggplot(mash, aes(x = mash[,i], y = log(shares), fill = mash[,i])) + 
				geom_boxplot() + labs(title = plot_title)
			print(p)
			
			dev.off()
		}
	}	

```



```{r spine plots, include = TRUE, message = FALSE}

# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	make some plots ...
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

	mash_plot <- subset (mash, select = c(2, 3, 4, 5, 6, 8, 9, 10,
												14, 15, 16, 17, 20, 22, 23, 24, 30, 31, 12))
	for (i in 1 : length(mash_plot))
	{
		if(class(mash_plot[,i]) == "integer" || class(mash_plot[,i]) == "factor")
		{
			png (filename = paste0(names(mash_plot[i]), "_%02d.png"), width = 500, height = 400)
			spineplot (factor(shot_good) ~ mash_plot[,i],
					data = mash_plot,
					col = c("#41ae76", "#8c96c6"),
					main = (names(mash_plot[i])),
					ylim = c(0.25, 0.75))
			dev.off()
		}
	}

```



```{r first model}

library(Amelia)
#missmap(mash, main = "Missing values vs observed")


# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	- choose factors based on visual of spine plots
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

	mash_baseline <- subset (mash, select = c(2, 3, 4, 5, 6, 8, 9, 10,
												14, 15, 16, 17, 20, 23, 24, 30, 31, 12, 13))
	
# ...	remove overtimes (until time_remaing is improved) !!
	
	mash_baseline <- mash_baseline[mash_baseline$period < 5,]
	
# ... 	remove test set rows
	
	mash_baseline <- mash_baseline[!is.na(mash_baseline$shot_made_flag) , ]

# ...	!! removed action_type for now due to types not common between traing set and test set
	
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	- choose factors based on visual of spine plots
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

	model <- glm(shot_made_flag ~ ., family = binomial(link = 'logit'), data = mash_baseline)

#	By using function summary() we obtain the results of our model:

	summary(model)
	
	mash_baseline$pred <- predict(model, na.action = na.exclude)
	mash_test$prob <- exp(mash_test$pred) / (1 + exp(mash_test$pred))
	mash_test$y_pred <- 0
	one_lst <- mash_test$prob >= 0.5
	mash_test$y_pred[one_lst] <- 1


```

```{r kaggle submit}


# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	submittal file - visually selected EVs
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

	mash_test <- mash[is.na(mash$shot_made_flag),]

	mash_test$pred <- predict(model, newdata = mash_test)
	mash_test$prob <- exp(mash_test$pred) / (1 + exp(mash_test$pred))
	mash_test$y_pred <- 0
	one_lst <- mash_test$prob >= 0.5
	mash_test$y_pred[one_lst] <- 1

	df_submit <- data.frame(mash_test$shot_id, mash_test$y_pred)
	names(df_submit) <- c("shot_id", "shot_made_flag")
	
	write.csv(df_submit, file = "submit_baseline_2017.08.20.csv", row.names = FALSE)
```

